version: "3"

services:
  springboot:
    build:
      context: ./
      dockerfile: Dockerfile
    image: lianshufeng/jrebel
    ports:
      - "8080:8080"
    working_dir: /opt/jar
    container_name: jrebel
    restart: always
   